# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true

# Mod Info
archives_base_name=Steam_Rails
mod_version=1.6.14-beta
maven_group=com.railwayteam.railways

minecraft_version=1.21.1

# Mappings
parchment_version=2024.01.01  # Parchment actualizado para 1.21.1

# NeoForge
neoforge_version=21.1.37

# Create - NeoForge
create_forge_version=6.0.8-NEOFORGE
create_forge_version_range=[6.0.7,)
ponder_version=1.0.91
registrate_forge_version=MC1.21-1.4.0
flywheel_version=1.1.0

# Mixin Extras
mixin_extras_version=0.4.0

# Development QOL
fabric_recipe_viewer=emi
jei_forge_version=11.6.1
rei_version=12.0.650
emi_version=1.1.0+1.21.1

# Mod Menu
modmenu_version=7.3.0
lazydfu_version=0.1.4

# Mod compatibility
enable_simple_voice_chat=false
enable_hexcasting=false
enable_byg=false
enable_bop=false
enable_natures_spirit=false
enable_dnd=false
enable_quark=false
enable_tfc=false
enable_sodium_rubidium=false
enable_iris=false
enable_tweakeroo=false
enable_sc=false

# Publishing
modrinth_id=ZzjhlDgM
curseforge_id=688231
